version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./artifacts:/app/artifacts
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    image: node:20
    working_dir: /frontend
    volumes:
      - ./app:/frontend/app
      - ./index.html:/frontend/index.html
    command: npx serve -s build -l 8000
    ports:
      - "3000:8000"
    depends_on:
      - backend
